sudo: required
dist: trusty
env:
- JDK_TAG=jdk-11+20
script:
- |
  if [ "${TRAVIS_PULL_REQUEST}" != "false" -o "${TRAVIS_BRANCH}" == "${TRAVIS_TAG}" ]
  then
    ./make-jdk-src-archive.sh ${JDK_TAG}
    ls -l
  fi
before_deploy:
- export SRC_ZIP=jdk-${JDK_TAG}.src.zip
- echo "SRC_ZIP=${SRC_ZIP}"
deploy:
  provider: releases
  api_key:
    secure: bn0giycL4mCHvt5zxuzfezUypUPOFjl/PbtLSqSVpgYbmwClwlFWhIwkofGMOyUK6WK9UI+KQLR6mrJEf74WfaTxHaSE9k5gD4elnzg51dc52I1+mjpByfKzolWgEyCdzQInk0svsAffcqcJ+zDj7vTUAAQ7RRn3KcczPRnqRZHMEbumzgUV9GLKB4zwH66UUXqvKJepixqgImG8aoV1YBAvwRxDDbMgA2uP1o1nawzBH7zcbRc84hd6wK0EjV1bGzMaUstjsO8nv4b7C1rgiipFSB/HEp7qXWGXfI814WbTfeKT/tqwVxkmV4DpA9HOXK5JFfWnFqMMawoPQ5joldlS1wY13EAaEeyNt8PLXSO+nXGbV00hnOSUCIOEnkE1DggnzH4EGwnL3Fwyh2HRR9/sXBvYNxtha9gRPSYgMp96Yk0qP/muD2qHbUZf/I6QahmZcZ9+bOzLv7BEzwr49OdCnMQB2vWTE1cn0P8JZ9ABFA/A+1I2anpvmEjfAAkWfPAUAfBBZNKrZkN7oUoaW6xXrVbk6m7b0IhspT/9wuRgaZfr7GXLCkh15XggHRdXNlKS2jl3tIiUP/waB5d7Oivtqeg+pvcsFhvj9piK22yuVRVyYpunL0vGfP7CboJexQB66wdzHtUEijvWPpyQmDSpNLML52pzRmV7O5GZ/1M=
  file:
  - "${SRC_ZIP}"
  - "${SRC_ZIP}.sha1"
  skip_cleanup: true
  on:
    tags: true
    repo: dougxc/jdk-sourcer
